---
title: "Tarea 04: Visualización preliminar de datos"
author: "Ana Paola Arias, Alejandro Gutiérrez, Sofía Palacios Cuevas,"
date: "23/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<div aling="justify">En esta actividad realizamos, mediante gráficos sencillos, una visualización preliminar de cada una de nuestras variables de interés.</div>

# **Variables relacionadas con la vivienda**

```{r}
library(ggplot2)
library(viridisLite)
library(hrbrthemes)
bd.original.vivienda<-read.csv("conjunto_de_datos_tvivienda_ecovid_ed_2020.csv")
bd.vivienda<-bd.original.vivienda[ ,-c(2,3,4,5,6,7,8,9,10,11,12,13,
                                         14,15,16,17,18,19,20,21,22,23,24,25,
                                         26,27,28,29, 64)]
write.csv(bd.vivienda, "bd.vivienda.csv")
######## Select the "B"Base_de_datos_por_vivienda.csv" from Files and ask to
# import"

# Lets rename our cured database
bd.vivienda<-read.csv("bd.vivienda.csv")
View(bd.vivienda)
```

# **TICs** {.tabset}
### **Dispositivos con los que cuentan en su vivienda por entidad federativa**
## **Computadora de escritorio**
```{r}
ce<-ggplot(bd.vivienda, aes(x=ENT, y=P2_1_1, fill=P2_1_1)) + 
  geom_bar(position="dodge",stat = "identity" ) +
  xlab("No. de Entidad Federativa") +
  ylab("Sí = 1, No = 2") +
  ggtitle("Dispocisión de computadora de escritorio por entidad" ) +
  theme(plot.title = element_text(size=16))
ce
```

## **Computadora portátil**
```{r}
cp<-ggplot(bd.vivienda, aes(x=ENT, y=P2_1_2, fill=P2_1_2)) + 
  geom_bar(position="dodge",stat = "identity" ) +
  xlab("No. de Entidad Federativa") +
  ylab("Sí = 1, No = 2") +
  ggtitle("Dispocisión de computadora portátil por entidad" ) +
  theme(plot.title = element_text(size=16))
cp
```

## **Televisión digital**
```{r}
tv<-ggplot(bd.vivienda, aes(x=ENT, y=P2_1_3, fill=P2_1_3)) + 
  geom_bar(position="dodge",stat = "identity" ) +
  xlab("No. de Entidad Federativa") +
  ylab("Sí = 1, No = 2") +
  ggtitle("Dispocisión de TV digital por entidad" ) +
  theme(plot.title = element_text(size=16))
tv
```
